name: Deploy Backend (Express)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Backend Dependencies
        run: npm install
        working-directory: backend


      - name: Upload Backend Code to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ${{ secrets.EC2_USER_BACK }}
          key: ${{ secrets.EC2_KEY_BACK }}
          source: "backend/"
          target: "/var/www/estudy-backend"
          rm: true
          strip_components: 1
      
      - name: Crear .env en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ${{ secrets.EC2_USER_BACK }}
          key: ${{ secrets.EC2_KEY_BACK }}
          script: |
            cd /var/www/estudy-backend
            cat > .env <<EOF DATABASE_URL=${{ secrets.DATABASE_URL }} PORT=${{ secrets.PORT }} JWT_SECRET=${{ secrets.JWT_SECRET }} DB_HOST=${{ secrets.DB_HOST }} DB_USER=${{ secrets.DB_USER }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_NAME=${{ secrets.DB_NAME }} DB_PORT=${{ secrets.DB_PORT }} AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} AWS_REGION=${{ secrets.AWS_REGION }} AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} EOF

      - name: Install and Restart Backend on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ${{ secrets.EC2_USER_BACK }}
          key: ${{ secrets.EC2_KEY_BACK }}
          script: |
            cd /var/www/estudy-backend
            npm install
            npx prisma generate
            pm2 restart estudy-backend || pm2 start src/app.js --name estudy-backend
            pm2 save


