name: Deploy Backend (Express)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Backend Dependencies
        run: npm install
        working-directory: backend


      - name: Upload Backend Code to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ${{ secrets.EC2_USER_BACK }}
          key: ${{ secrets.EC2_KEY_BACK }}
          source: "backend/"
          target: "/var/www/estudy-backend"
          rm: true
          strip_components: 1
      
      - name: Crear .env en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ${{ secrets.EC2_USER_BACK }}
          key: ${{ secrets.EC2_KEY_BACK }}
          script: |
            cd /var/www/estudy-backend
            printf "DATABASE_URL=%s\nPORT=%s\nJWT_SECRET=%s\nDB_HOST=%s\nDB_USER=%s\nDB_PASSWORD=%s\nDB_NAME=%s\nDB_PORT=%s\nAWS_ACCESS_KEY_ID=%s\nAWS_SECRET_ACCESS_KEY=%s\nAWS_REGION=%s\nAWS_BUCKET_NAME=%s\n" \
            "${{ secrets.DATABASE_URL }}" \
            "${{ secrets.PORT }}" \
            "${{ secrets.JWT_SECRET }}" \
            "${{ secrets.DB_HOST }}" \
            "${{ secrets.DB_USER }}" \
            "${{ secrets.DB_PASSWORD }}" \
            "${{ secrets.DB_NAME }}" \
            "${{ secrets.DB_PORT }}" \
            "${{ secrets.AWS_ACCESS_KEY_ID }}" \
            "${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            "${{ secrets.AWS_REGION }}" \
            "${{ secrets.AWS_BUCKET_NAME }}" > .env

      - name: Install and Restart Backend on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_BACK }}
          username: ${{ secrets.EC2_USER_BACK }}
          key: ${{ secrets.EC2_KEY_BACK }}
          script: |
            cd /var/www/estudy-backend
            npm install
            npx prisma generate
            pm2 restart estudy-backend || pm2 start src/app.js --name estudy-backend
            pm2 save


